apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: capstone
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: mayuridhote/capstone:${GIT_COMMIT} 
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
        env:
          - name: MONGODB_HOST
            value: "mongodb-0.mongodb"
          - name: MONGODB_DB
            value: "notesdb"
          - name: PORT
            value: "4000"